CLEAN(I/O) Remove StreamToPDU and posix-read
scality/kineticlib pull request #56
Opened 2016-10-14 15:36 UTC by AntoninCoulibaly

The streamToPDU function was doing I/O but in the library it could be
better to not having I/O.
The I/O should be done by the library user.

2016-10-14 15:45 UTC, michael-zapata commented
Glad to see this coming to fruitition!

2016-10-17 08:30 UTC, ghost requested changes
This is great!

But we should also edit the documentation accordingly (README.md).

2016-10-17 08:30 UTC, michael-zapata commented on lib/kinetic.js
> +
Nit: No need for this line here.

2016-10-18 14:49 UTC, AntoninCoulibaly commented
@michael-zapata ok I'm on it. it will be in a separate PR

2016-10-18 14:55 UTC, MathieuCassagne approved these changes

2016-10-18 15:06 UTC, ghost approved these changes

2016-10-18 15:06 UTC, michael-zapata commented
Just add an issue when you merge this one, so that we're clear the doc is outdated.

2016-10-18 16:36 UTC, AntoninCoulibaly commented
@michael-zapata  perfect thank you thank you. I'm adding it to the project

2016-10-18 17:35 UTC, merged